In [2]:
import numpy as np

In [48]:
arr = []
for i in range(91):
    r = []
    for j in range(91):
        if j == 0:
            r.append(round(0.10 + 0.01*i,2))
        elif j == i + 1:
            r.append(round(0.90 - 0.01*i, 2))
        else:
            r.append(0.00)
    arr.append(r)
    
np_arr = np.array(arr)
print(np_arr)

transition_matrix_transp = np_arr.T
eigenvals, eigenvects = np.linalg.eig(transition_matrix_transp)

close_to_1_idx = np.isclose(eigenvals,1)
target_eigenvect = eigenvects[:,close_to_1_idx]
target_eigenvect = target_eigenvect[:,0]

# Turn the eigenvector elements into probabilites
stationary_distrib = target_eigenvect / sum(target_eigenvect) 

stationary_distrib

[[0.1  0.9  0.   ... 0.   0.   0.  ]
 [0.11 0.   0.89 ... 0.   0.   0.  ]
 [0.12 0.   0.   ... 0.   0.   0.  ]
 ...
 [0.98 0.   0.   ... 0.   0.02 0.  ]
 [0.99 0.   0.   ... 0.   0.   0.01]
 [1.   0.   0.   ... 0.   0.   0.  ]]


array([1.46097542e-01+0.j, 1.31487788e-01+0.j, 1.17024131e-01+0.j,
       1.02981235e-01+0.j, 8.95936746e-02+0.j, 7.70505602e-02+0.j,
       6.54929762e-02+0.j, 5.50141000e-02+0.j, 4.56617030e-02+0.j,
       3.74425964e-02+0.j, 3.03285031e-02+0.j, 2.42628025e-02+0.j,
       1.91676140e-02+0.j, 1.49507389e-02+0.j, 1.15120690e-02+0.j,
       8.74917240e-03+0.j, 6.56187930e-03+0.j, 4.85579068e-03+0.j,
       3.54472720e-03+0.j, 2.55220358e-03+0.j, 1.81206454e-03+0.j,
       1.26844518e-03+0.j, 8.75227175e-04+0.j, 5.95154479e-04+0.j,
       3.98753501e-04+0.j, 2.63177311e-04+0.j, 1.71065252e-04+0.j,
       1.09481761e-04+0.j, 6.89735096e-05+0.j, 4.27635759e-05+0.j,
       2.60857813e-05+0.j, 1.56514688e-05+0.j, 9.23436658e-06+0.j,
       5.35593262e-06+0.j, 3.05288159e-06+0.j, 1.70961369e-06+0.j,
       9.40287531e-07+0.j, 5.07755267e-07+0.j, 2.69110291e-07+0.j,
       1.39937351e-07+0.j, 7.13680492e-08+0.j, 3.56840246e-08+0.j,
       1.74851721e-08+0.j, 8.39288259e-09+0.j, 3.94465482e-09+

In [101]:
import numpy as np

# Matrix Creation
size = 91
arr = np.zeros((size, size))
arr[:, 0] = np.round(0.10 + 0.01 * np.arange(size), 2)
np.fill_diagonal(arr[:, 1:], np.round(0.90 - 0.01 * np.arange(size), 2))

# Eigenvalue and Eigenvector Computation
transition_matrix_transp = arr.T
eigenvals, eigenvects = np.linalg.eig(transition_matrix_transp)

# Find the Eigenvector Corresponding to Eigenvalue Close to 1
close_to_1_idx = np.isclose(eigenvals, 1)
target_eigenvect = eigenvects[:, close_to_1_idx].flatten()

# Normalize the Eigenvector to get Stationary Distribution
stationary_distrib = target_eigenvect / target_eigenvect.sum()

# print(stationary_distrib)

# trying
print(arr)

# To compute the stationary distribution iteratively given the transition matrix
# we can iteratively from t 0 to whatever big number till convergence
# compute each state probaility at t+1 by multiply the probilities going into each state given by the transition prob by the prev distibution policy

# so start with a random distirbution and iterate it by setting it equal to all the transitions going into it
# the sum of the the probabilities X transitions given other states of going into this current state. 
# so the proababiliity of entering this state given all states
# the sum over all state : prob of entering this state times the policy of being at that state
# for policy_t+1(1) = 0.1 policy_t(1) + 0.11 policy_t(2) + 0.12 policy_t(3)

# start with some distribution

init_dist = np.array([1.0] + [0.0] * 90 )
init_dist = np.random.uniform(size=91)

# # loop through each state
# for state_i in range(1):
#     # sum of columns
#     # because that is the prob of entering each state
    
#     # proability of y given x
#     p_xy = arr[:, state_i]
    
#     init_dist[state_i] = sum(init_dist[state_i] * p_xy)
    


for i in range(1000):
    # dist_t+1 = sum
    init_dist = arr.T.dot(init_dist) 
  
# init_dist  
# sum(arr[:, 0] * init_dist)
# update the distributions based on the transitions and the previous distirbution

# np.linalg.solve(arr.T, init_dist)
init_dist
# init_dist
# arr



[[0.1  0.9  0.   ... 0.   0.   0.  ]
 [0.11 0.   0.89 ... 0.   0.   0.  ]
 [0.12 0.   0.   ... 0.   0.   0.  ]
 ...
 [0.98 0.   0.   ... 0.   0.02 0.  ]
 [0.99 0.   0.   ... 0.   0.   0.01]
 [1.   0.   0.   ... 0.   0.   0.  ]]


array([6.58459943e+00, 5.92613949e+00, 5.27426414e+00, 4.64135245e+00,
       4.03797663e+00, 3.47265990e+00, 2.95176091e+00, 2.47947917e+00,
       2.05796771e+00, 1.68753352e+00, 1.36690215e+00, 1.09352172e+00,
       8.63882161e-01, 6.73828085e-01, 5.18847626e-01, 3.94324196e-01,
       2.95743147e-01, 2.18849929e-01, 1.59760448e-01, 1.15027522e-01,
       8.16695409e-02, 5.71686786e-02, 3.94463883e-02, 2.68235440e-02,
       1.79717745e-02, 1.18613712e-02, 7.70989126e-03, 4.93433040e-03,
       3.10862816e-03, 1.92734946e-03, 1.17568317e-03, 7.05409901e-04,
       4.16191842e-04, 2.41391268e-04, 1.37593023e-04, 7.70520928e-05,
       4.23786510e-05, 2.28844716e-05, 1.21287699e-05, 6.30696036e-06,
       3.21654978e-06, 1.60827489e-06, 7.88054697e-07, 3.78266255e-07,
       1.77785140e-07, 8.17811642e-08, 3.68015239e-08, 1.61926705e-08,
       6.96284832e-09, 2.92439630e-09, 1.19900248e-09, 4.79600993e-10,
       1.87044387e-10, 7.10768671e-11, 2.62984408e-11, 9.46743870e-12,
      

### Q B

In [103]:
import numpy as np

# Define the size of the matrix (91x91)
matrix_size = 91

# Initialize a 91x91 matrix with zeros
transition_matrix = np.zeros((matrix_size, matrix_size))

# Set the first column of the matrix with increasing values starting from 0.10
# The increment is 0.01 for each subsequent row
transition_matrix[:, 0] = np.round(0.10 + 0.01 * np.arange(matrix_size), 2)

# Fill the diagonal right to the main diagonal with decreasing values starting from 0.90
# The decrement is 0.01 for each subsequent element
np.fill_diagonal(transition_matrix[:, 1:], np.round(0.90 - 0.01 * np.arange(matrix_size), 2))

# Transpose the matrix to get the transition matrix in the required form
transposed_matrix = transition_matrix.T

# Calculate eigenvalues and eigenvectors of the transposed matrix
eigenvalues, eigenvectors = np.linalg.eig(transposed_matrix)
# print(eigenvalues)

# Find the index of the eigenvalue that is closest to 1
# This corresponds to the stationary distribution
eigenvalue_close_to_1_index = np.isclose(eigenvalues, 1)
# print(eigenvalue_close_to_1_index)

# Extract the eigenvector associated with the eigenvalue close to 1
target_eigenvector = eigenvectors[:, eigenvalue_close_to_1_index].flatten()
# print(target_eigenvector)

# Normalize the target eigenvector to get probabilities
# This represents the stationary distribution of the Markov chain
stationary_distribution = target_eigenvector / target_eigenvector.sum()

print(stationary_distribution @ ([1.0] + [0.0] * 90))
# print(transition_matrix)
# print(target_eigenvector)
# print(transposed_matrix)


(0.14609754173593165+0j)


### Q C

In [98]:

initial_dist = np.array([1]+([0] * 90))

for _ in range(10000):
    update = initial_dist @ transition_matrix
    initial_dist = update
    
print(initial_dist)


[1.46097542e-01 1.31487788e-01 1.17024131e-01 1.02981235e-01
 8.95936746e-02 7.70505602e-02 6.54929762e-02 5.50141000e-02
 4.56617030e-02 3.74425964e-02 3.03285031e-02 2.42628025e-02
 1.91676140e-02 1.49507389e-02 1.15120690e-02 8.74917240e-03
 6.56187930e-03 4.85579068e-03 3.54472720e-03 2.55220358e-03
 1.81206454e-03 1.26844518e-03 8.75227175e-04 5.95154479e-04
 3.98753501e-04 2.63177311e-04 1.71065252e-04 1.09481761e-04
 6.89735096e-05 4.27635759e-05 2.60857813e-05 1.56514688e-05
 9.23436658e-06 5.35593262e-06 3.05288159e-06 1.70961369e-06
 9.40287531e-07 5.07755267e-07 2.69110291e-07 1.39937351e-07
 7.13680492e-08 3.56840246e-08 1.74851721e-08 8.39288259e-09
 3.94465482e-09 1.81454122e-09 8.16543547e-10 3.59279161e-10
 1.54490039e-10 6.48858164e-11 2.66031847e-11 1.06412739e-11
 4.15009682e-12 1.57703679e-12 5.83503613e-13 2.10061301e-13
 7.35214552e-14 2.49972948e-14 8.24910728e-15 2.63971433e-15
 8.18311442e-16 2.45493433e-16 7.11930954e-17 1.99340667e-17
 5.38219801e-18 1.399371

In [142]:
import numpy as np

def compute_stationary_distribution(transition_matrix, tolerance=1e-10, max_iterations=1000):
    # Initialize a uniform distribution
    distribution = np.ones(transition_matrix.shape[0]) / transition_matrix.shape[0]
    
    for _ in range(max_iterations):
        new_distribution = np.dot(distribution, transition_matrix)
        
        # Check for convergence
        if np.linalg.norm(new_distribution - distribution) < tolerance:
            return new_distribution
        
        distribution = new_distribution

    raise ValueError("Stationary distribution did not converge within the maximum number of iterations")

# Define the size of the matrix (91x91)
matrix_size = 91

# Initialize a 91x91 matrix with zeros
transition_matrix = np.zeros((matrix_size, matrix_size))

# Set the first column and the diagonal right to the main diagonal
transition_matrix[:, 0] = np.round(0.10 + 0.01 * np.arange(matrix_size), 2)
np.fill_diagonal(transition_matrix[:, 1:], np.round(0.90 - 0.01 * np.arange(matrix_size), 2))

# Transpose the matrix for correct orientation of the transition matrix
transposed_matrix = transition_matrix.T

# Compute the stationary distribution iteratively
stationary_distribution = compute_stationary_distribution(transposed_matrix)

print(stationary_distribution)


[0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901
 0.01098901 0.01098901 0.01098901 0.01098901 0.01098901 0.0109

In [113]:
for i in range(len(transition_matrix)):
    print(f'{i}: ', transition_matrix[i])

0:  [0.1 0.9 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0. ]
1:  [0.11 0.   0.89 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.  ]
2:  [0.12 0.   0.   0.88 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.

In [61]:

a = np.array([[-1, 0, 1], [1, -1, 1], [-0.5, 1, 1]])
b = np.array([0, 1, 2])
np.linalg.solve(a, b)

array([1.2, 1.4, 1.2])

In [110]:
tarr = []
for i in range(91):
    tr = [0]
    for j in range(93):
        if j == i:
            tr.append(-round(0.90 - 0.01*i, 2))
        else:
            tr.append(0.00)
    
    if i == 0:
        tr[-1] = 1
    if i != 0:
        tr[i] = 1
    tr[j] = 1    
    
    tarr.append(tr)
    
a = np.array(tarr)
b = np.array([1] + [0]*93)

np.linalg.solve(a, b)

LinAlgError: Last 2 dimensions of the array must be square

### Q D

In [119]:
import numpy as np

tarr = []
matrix_size = 91  # Define the size of the matrix

for i in range(matrix_size):
    tr = [0] * (matrix_size)  # Initialize a row with zeros
    tr[i] = -round(0.90 - 0.01 * i, 2)  # Set the diagonal element

    if i != 0:
        tr[i-1] = 1  # Set the 1's in the subdiagonal
    tr[-1] = 1

    tarr.append(tr)
    

a = np.array(tarr)
b = np.array([1] + [0] * (matrix_size-2) + [1])

solution = np.linalg.solve(a, b)
print(solution)

# a
# solution = V2, V3, V4, ...., theta

# for i in range(len(a)):
#     print(f'V{i+2}', a[i])




[-0.94878051 -0.90189097 -0.85885617 -0.8192628  -0.7827503  -0.74900324
 -0.71774488 -0.68873173 -0.66174901 -0.63660675 -0.61313651 -0.59118857
 -0.57062952 -0.55134024 -0.53321407 -0.51615537 -0.50007815 -0.48490494
 -0.47056584 -0.4569976  -0.44414294 -0.43194985 -0.42037104 -0.40936343
 -0.39888771 -0.38890795 -0.37939126 -0.3703075  -0.36162896 -0.35333019
 -0.34538775 -0.33778001 -0.33048702 -0.32349031 -0.3167728  -0.31031866
 -0.30411317 -0.2981427  -0.29239454 -0.28685686 -0.28151864 -0.27636959
 -0.27140009 -0.26660117 -0.26196441 -0.25748194 -0.25314636 -0.24895074
 -0.24488856 -0.2409537  -0.2371404  -0.23344323 -0.22985707 -0.22637709
 -0.22299875 -0.21971774 -0.21652999 -0.21343165 -0.21041908 -0.20748883
 -0.20463763 -0.20186238 -0.19916012 -0.19652807 -0.19396356 -0.19146407
 -0.18902719 -0.18665063 -0.18433221 -0.18206986 -0.17986159 -0.17770551
 -0.17559982 -0.17354279 -0.17153277 -0.1695682  -0.16764757 -0.16576943
 -0.16393241 -0.16213519 -0.1603765  -0.15865514 -0

### Long run average

In [125]:
b

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1])

In [124]:
np.sum(b * stationary_distribution)

(0.14609754173593165+0j)

In [105]:
import numpy as np

matrix_size = 91
tarr = np.zeros((matrix_size, matrix_size))

# Populate the matrix according to your rules
for i in range(matrix_size):
    if i != 0:
        tarr[i, i - 1] = 1  # Set subdiagonal elements
    tarr[i, i] = -round(0.90 - 0.01 * i, 2)  # Set diagonal elements

# Handle the special cases for the first and last rows
tarr[0, 0] = 1
tarr[-1, -1] = 1
tarr[-1, -2] = 0

# Vector b with 1 in the first position and 0s elsewhere
b = np.zeros(matrix_size)
b[0] = 1

# Solve the system
solution = np.linalg.solve(tarr, b)
print(solution)

tarr


[1.00000000e+00 1.12359551e+00 1.27681307e+00 1.46760124e+00
 1.70651306e+00 2.00766243e+00 2.39007432e+00 2.87960761e+00
 3.51171660e+00 4.33545260e+00 5.41931574e+00 6.85989335e+00
 8.79473506e+00 1.14217338e+01 1.50285972e+01 2.00381296e+01
 2.70785534e+01 3.70939088e+01 5.15193178e+01 7.25624195e+01
 1.03660599e+02 1.50232753e+02 2.20930518e+02 3.29747042e+02
 4.99616731e+02 7.68641125e+02 1.20100176e+03 1.90635200e+03
 3.07476128e+03 5.04059227e+03 8.40098711e+03 1.42389612e+04
 2.45499331e+04 4.30700581e+04 7.69108180e+04 1.39837851e+05
 2.58958983e+05 4.88601855e+05 9.39618952e+05 1.84239010e+06
 3.68478021e+06 7.51995960e+06 1.56665825e+07 3.33331543e+07
 7.24633788e+07 1.61029731e+08 3.65976661e+08 8.51108513e+08
 2.02644884e+09 4.94255815e+09 1.23563954e+10 3.16830651e+10
 8.33764870e+10 2.25341857e+11 6.25949602e+11 1.78842743e+12
 5.26008069e+12 1.59396385e+13 4.98113702e+13 1.60681839e+14
 5.35606131e+14 1.84691769e+15 6.59613462e+15 2.44301282e+16
 9.39620316e+16 3.758481

array([[ 1.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 1.  , -0.89,  0.  , ...,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  1.  , -0.88, ...,  0.  ,  0.  ,  0.  ],
       ...,
       [ 0.  ,  0.  ,  0.  , ..., -0.02,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  1.  , -0.01,  0.  ],
       [ 0.  ,  0.  ,  0.  , ...,  0.  ,  0.  ,  1.  ]])

In [365]:
max_iterations = 10
count = 0
terminate = False

# 0. Fix a policy
policy = np.array([0] * 91)
poisson_a = np.copy(a)
poisson_b = np.array([0.0] * (91))
    
while terminate == False and count < max_iterations:
    # print(f'ITERATION: {count+1}')
    # 1. Find a solution for poisson equation  
    
    for i in range(len(policy)):
        if i == 0:
            poisson_b[i] = 1
        elif policy[i] == 1:
            poisson_b[i] = 0.6
    
    new_val = np.linalg.solve(poisson_a, poisson_b)
    print('NEW VALUES: ', new_val[-1])

    # 2. Determine argmax (min)
    a2 = 0.6
    new_policy = []
    for i in range(len(new_val)):
        
        if i != 90:
            a1 = new_val[i]*transition_matrix[i][i+1] + 1 
        else:
            a1 = 1
        
        argmin = np.argmin([a1, a2])
        # print(f'v{i+1}', a1, a2, argmin)
        new_policy.append(argmin)
        
    
    new_policy_np = np.array(new_policy)

    # 3. Check if policies are the same
    terminate =  np.array_equal(policy, new_policy_np)
    if terminate == True:
        # print('done')
        break
    else:
        policy = new_policy 
        count += 1
    

print(policy)
print(new_policy)
print(count)

NEW VALUES:  0.14609754173593134
NEW VALUES:  0.16525672176998518
NEW VALUES:  0.3475565835687272
NEW VALUES:  0.6584390166943722
NEW VALUES:  0.6584390166943722
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
4


In [201]:
np.array_equal([1,2,3], [1,2,3])

True

In [ ]:
# print(policy)
# print(poisson_b)

# find a solution to poisson equation, v & theta
# np.array(policy)
# print(transition_matrix)

# policy eval
# from QD jsut updates the b vector to be 0.6 instead of 0 when action 2


print(transition_matrix)
print(new_val)

In [241]:
# State
# Action
# Reward
# Transition
class MDP:
    def __init__(self):
        pass
    
    def get_states(self):
        pass
    
    def get_transition(self, state, action):
        pass
    
    def get_reward(self, state, action, next_state):
        pass
    
    def get_initial_state(self):
        pass
    

In [ ]:
class Policy():

In [234]:
import math

In [238]:
math.e / math.e**(sum([1,2,3]))

0.006737946999085469

In [239]:
import numpy as np

# Define Q(a) function arbitrarily, for example, as a quadratic function
def Q(a):
    return -a**2

# Define the temperature parameter tau
tau = 1.0

# Let's create a range of possible states a, for example from -10 to 10
states = np.arange(-10, 10, 0.1)

# Calculate the probabilities for each state using the Boltzmann distribution
probabilities = np.exp(Q(states) / tau)

# Normalize the probabilities so they sum to 1
probabilities /= np.sum(probabilities)

# Let's look at the first 10 probabilities to keep the output concise
probabilities[:10]


array([2.09882812e-45, 1.53540479e-44, 1.10098911e-43, 7.73850845e-43,
       5.33145332e-42, 3.60037777e-41, 2.38322279e-40, 1.54630558e-39,
       9.83422443e-39, 6.13054405e-38])

$x = 5$

In [242]:
V = np.zeros(3)
r1 = np.array([0, 1, 2])
r2 = np.array([0, 1, 3])

P1 = np.array([
    [0, 1, 0],
    [0, 0, 1],
    [0.5, 0.5, 0]
])
P2 = np.array([
    [0, 1, 0],
    [0, 0, 1],
    [1, 0, 0]
])



In [246]:
r1 + P1 @ V

array([0., 1., 2.])

In [247]:
V_new = np.maximum(r1 + P1.dot(V), r2 + P2.dot(V))

In [249]:
a = np.argmax([np.dot(r1[2] + P1[2, :], V), np.dot(r2[2] + P2[2, :], V)])
a

0

In [251]:
V = np.array([0, 0, 0], dtype=float)
r1 = np.array([0, 1, 2], dtype=float)
r2 = np.array([0, 1, 3], dtype=float)

P1 = np.array([[0, 1, 0], [0, 1, 0.5], [0, 0.5, 0.5]], dtype=float)
P2 = np.array([[0, 1, 0], [0, 1, 1], [0, 0, 0]], dtype=float)


In [120]:
for n in range(1, 10):
    V_new = np.maximum(r1 + P1.dot(V), r2 + P2.dot(V))
    a = np.argmax([np.dot(r1[2] + P1[2, :], V), np.dot(r2[2] + P2[2, :], V)])
    V = V_new - np.min(V_new)
    if a == 0:
        V = r1 + P1.dot(V) - V
    else:
        V = r2 + P2.dot(V) - V

V

NameError: name 'r1' is not defined

In [283]:

# Initialize the vectors and matrices
V = np.array([0, 0, 0], dtype=float)  # Equivalent to V in R
r1 = np.array([0, 1, 2], dtype=float)  # Equivalent to r1 in R
r2 = np.array([0, 1, 3], dtype=float)  # Equivalent to r2 in R

# P1 and P2 are matrices equivalent to P1 and P2 in R
P1 = 0.5 * np.array([[0, 1, 0], [0, 0, 1], [0.5, 0.5, 0]], dtype=float)
P2 = 0.5 * np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]], dtype=float)

In [ ]:
P1 = np.array([[]])

In [121]:

# Start a loop that will run 100 times
for n in range(1, 5):
    # Calculate the element-wise maximum of two vector-matrix products added to r1 and r2
    V_new = np.maximum(r1 + P1.dot(V), r2 + P2.dot(V))
    
    # Determine which combination gives the maximum value at the third position
    a = np.argmax([np.dot(r1[2] + P1[2, :], V), np.dot(r2[2] + P2[2, :], V)])
    print(a)
    # Update V by subtracting the minimum value of the new V to normalize
    V = V_new - np.min(V_new)
    
    # Depending on the value of 'a', update V using a different combination of r1/r2 and P1/P2
    if a == 0:
        V = r1 + P1.dot(V) - V
    else:
        V = r2 + P2.dot(V) - V

# The final result stored in V
V

NameError: name 'r1' is not defined

In [265]:
a

1

In [273]:
V_new = np.maximum(r1 + P1 @ V, r2, + P2 @ V)

In [270]:
np.maximum([1,2,3,4], [2,10,11, 3])

array([ 2, 10, 11,  4])

In [274]:
V_new

array([0., 1., 3.])

In [288]:
transition_matrix

array([[0.1 , 0.9 , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.11, 0.  , 0.89, ..., 0.  , 0.  , 0.  ],
       [0.12, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       ...,
       [0.98, 0.  , 0.  , ..., 0.  , 0.02, 0.  ],
       [0.99, 0.  , 0.  , ..., 0.  , 0.  , 0.01],
       [1.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ]])

In [115]:
V_prev = np.array([0.0] * 91)
action1_r = np.copy(b)
action2_r = np.array([0.6] * 91)
p_matrix = np.copy(transition_matrix)

for j in range(5):
    V_new = np.minimum(p_matrix.dot(V_prev) + 1, V_prev[0] + 0.6)
    print(V_prev - V_new)
    
    V_prev = V_new

In [123]:
# V_action1 = 
for j in range(5):
    V_new = np.minimum(p_matrix.dot(V_prev) + 1, V_prev[0] + 0.6)
    print(V_prev - V_new)
    
    V_prev = V_new
    
    

[-0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6]
[-0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6]
[-0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6 -0.6
 -0

In [380]:
P_1 = np.copy(transition_matrix)
V = np.array([0.0] * 89)
R_1 = np.array([1.0] + ([0.0] * 89) + [1.0])
threshold = 0.1

In [383]:
for i in range(len(P_1)):
    print(f'{i} : {P_1[i]}')

0 : [0.1 0.9 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0. ]
1 : [0.11 0.   0.89 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.  ]
2 : [0.12 0.   0.   0.88 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.

In [371]:
np.minimum()

0.9

In [ ]:
tarr = []
matrix_size = 91

for i in range(matrix_size):
    tr = [0] * (matrix_size) 
    tr[i] = -round(0.90 - 0.01 * i, 2)

    if i != 0:
        tr[i-1] = 1  # Set the 1's in the subdiagonal
    tr[-1] = 1

    tarr.append(tr)
    
print(np.array(tarr))
